export const MODE_READ = "STATE.MODE_READ";
export const MODE_WRITE = "STATE.MODE_WRITE";

export const CHANGE_PRIMARY_LANG = "STATE.CHANGE_PRIMARY_LANGUAGE";
export const CHANGE_SOURCE_LANG = "STATE.CHANGE_SOURCE_LANGUAGE";

export const EDITOR_DATA_CHANGED = "STATE.EDITOR_DATA_CHANGED";

export const READER_NEW_TRANSLATION = "STATE.ADD_NEW_TRANSLATION";